type tPriority = "Top" | "High" | "Mid" | "Low" | "No" | "unassigned";

interface tQuestions {
    questions: tQuestionsEntity[];
    tags: string[];
    who: string[];
    where: string[];
}

interface tQuestionsEntity {
    question: string;
    potentialAnswers: string[];
    followups: string[];
    references: string[];
    priority: tPriority;
    tags: string[];
    who: string[];
}

const data: tQuestions = {
    questions: [
        {
            question: "If you could wave a magic wand and change anything about the company, what would it be?",
            potentialAnswers: ["Prefer technical issues; they are generally easier to fix than people issues."],
            followups: ["Anything else you would change?"],
            references: ["https://news.ycombinator.com/item?id=11449133"],
            priority: "High",
            tags: ["#issues"],
            who: [],
        },
        {
            question: "Could your manager step in and do your job if necessary?",
            potentialAnswers: [
                "Yes (perhaps with some period of getting up to speed, etc.). Research shows that \"the benefit of having a highly competent boss is easily the largest positive influence on a typical worker's level of job satisfaction.\" Avoid working for non-technical management. Work for a manager who understands what their reports do, the complexity and level of effort of tasks, can help you with technical problems, can critically evaluate alternatives, and detect bullshit. Work where people are hired and promoted because they are capable and respected. Ideally every manager up to and including the CEO is technical.",
            ],
            followups: ["Could your manager's manager? The CEO?"],
            references: [
                "http://www.algeri-wong.com/yishan/engineering-management-technical-leaders.html",
                "https://hbr.org/2016/12/if-your-boss-could-do-your-job-youre-more-likely-to-be-happy-at-work",
            ],
            priority: "High",
            tags: ["#management"],
            who: [],
        },
        {
            question: "Would you say you learn more from your co-workers or on your own?",
            potentialAnswers: [
                "Work with people who know more, different things than you so you can learn and grow. Work where people hold their colleagues in high esteem and have the humility to say it.",
            ],
            priority: "High",
            tags: ["#culture"],
            followups: [],
            references: [],
            who: [],
        },
        {
            question: "Would you say your colleagues are good at reading your emotional state, or still learning?",
            potentialAnswers: [
                'Research shows the most important factor in team effectiveness is psychological safety, a "shared belief held by members of a team that the team is safe for interpersonal risk-taking." One component of this is high "average social sensitivity," or that everyone is good at reading the emotional state of others.',
            ],
            followups: ["Do you feel like your opinion is heard, respected, and valued?"],
            references: [
                "http://www.nytimes.com/2016/02/28/magazine/what-google-learned-from-its-quest-to-build-the-perfect-team.html",
            ],
            priority: "High",
            tags: ["#culture"],
            who: [],
        },
        {
            question:
                "In meetings (or discussions) specifically, what's the range of talkativeness between the most quiet person and the most vocal?",
            potentialAnswers: [
                'Research shows the most important factor in team effectiveness is psychological safety, a "shared belief held by members of a team that the team is safe for interpersonal risk-taking." One component of this is conversational turn-taking, or that everyone talks roughly the same amount.',
            ],
            references: [
                "http://www.nytimes.com/2016/02/28/magazine/what-google-learned-from-its-quest-to-build-the-perfect-team.html",
            ],
            priority: "High",
            tags: ["#culture"],
            followups: [],
            who: [],
        },
        {
            question: "How are hiring decisions made?",
            potentialAnswers: [
                "Five or six technical interviewers vote via secret ballot; all must agree (except perhaps one junior engineer), or it's a no-hire. No one should be able to hire unilaterally or override the vote of someone else; everyone should have unilateral veto power. The cost of a poor hire is far greater than the cost of missing a good hire.",
            ],
            followups: [
                "Does anyone have authority to hire unilaterally?",
                "Does anyone have authority to veto unilaterally?",
                "Do you feel like the process and your voice is always respected?",
            ],
            priority: "High",
            references: [
                "http://www.joelonsoftware.com/articles/GuerrillaInterviewing3.html",
                "http://www.algeri-wong.com/yishan/engineering-management.html",
            ],
            tags: ["#process", "#culture", "#hiring"],
            who: [],
        },
        {
            question: "Can I meet the people I will be working with? The manager?",
            potentialAnswers: [
                "Yes. The people you work with are one of the biggest determinants of job satisfaction. Push hard to follow up on this one.",
            ],
            priority: "High",
            who: ["#manager", "#hr"],
            tags: ["#culture"],
            followups: [],
            references: [],
        },
        {
            question: "Will I be responsible for system uptime? Part of any on-call rotation?",
            priority: "High",
            tags: ["#culture", "#issues"],
            potentialAnswers: [],
            followups: [],
            references: [],
            who: [],
        },
        {
            question: "How often do you get feedback in a year?",
            followups: ["Is it written or verbal?"],
            potentialAnswers: [],
            priority: "High",
            references: [],
            tags: ["#people", "#technical", "#feedback"],
            who: [],
        },
        {
            question: "How many hours did you work last week?",
            potentialAnswers: ["Working more than 40-hour weeks regularly decreases productivity."],
            followups: ["Is that typical?"],
            references: ["https://www.salon.com/2012/03/14/bring_back_the_40_hour_work_week/"],
            priority: "Mid",
            tags: ["#culture"],
            who: [],
        },
        {
            question: "How many meetings were you in in the last few days, and how long did they last?",
            followups: ["Is that typical?"],
            priority: "Mid",
            tags: ["#culture"],
            potentialAnswers: [],
            references: [],
            who: [],
        },
        {
            question: 'Where do you fall on the spectrum of "Do it right" to "Get-R-Done"?',
            potentialAnswers: ["The answer should align with your personal preference, but beware the extremes."],
            followups: ["Where would you say your team / manager / the company falls?"],
            priority: "Mid",
            tags: ["#culture"],
            references: [],
            who: [],
        },
        {
            question: "What sort of software development process / methodology do you use?",
            potentialAnswers: ['They should have one, preferably in the general area of "Agile."'],
            followups: ["How long are sprints?", "How do you feel it works for your team?"],
            priority: "Mid",
            tags: ["#process"],
            references: [],
            who: [],
        },
        {
            question: "How long does a build take?",
            potentialAnswers: ["Shorter is better."],
            priority: "Mid",
            tags: ["#technical", "#process"],
            followups: [],
            references: [],
            who: [],
        },
        {
            question: "Describe your build / deploy process.",
            potentialAnswers: ["There should be a process, ideally automated to a single step."],
            followups: ["How often does it break? Why?", "Is it documented?"],
            priority: "Mid",
            references: ["http://www.joelonsoftware.com/articles/fog0000000043.html"],
            tags: ["#technical", "#process"],
            who: [],
        },
        {
            question: "How often do you build / deploy?",
            potentialAnswers: ["More is better."],
            followups: ["How do you know if the deploy broke anything?"],
            priority: "Mid",
            references: ["http://www.joelonsoftware.com/articles/fog0000000043.html"],
            tags: ["#process"],
            who: [],
        },
        {
            question: "Do you have unit tests?",
            potentialAnswers: ['Beware "That\'s something we\'re working on," "We\'d really like to get there," etc.'],
            followups: ["How long does the test suite take to run?", "What is the code coverage?"],
            priority: "Mid",
            tags: ["#technical", "#process"],
            references: [],
            who: [],
        },
        {
            question: "How would you gauge your technical debt?",
            potentialAnswers: ["Lower is better, but an explicit process to manage it is even better."],
            followups: ["Do you have a process for managing it?"],
            priority: "Mid",
            tags: ["#process"],
            references: [],
            who: [],
        },
        {
            question: "How do you decide what goes into the next release?",
            potentialAnswers: [
                "Engineers should have a (large) say, and bug fixing, refactoring, and addressing technical debt should be prioritized or at least given official time.",
            ],
            priority: "Mid",
            tags: ["#process"],
            followups: [],
            references: [],
            who: [],
        },
        {
            question: "What tools do you use for communication and collaboration?",
            potentialAnswers: [
                "Know whether you prefer working at a desktop-and-e-mail kind of place or a laptop-and-IM kind of place.",
            ],
            followups: ["Are there plans to investigate or move to new systems in the future?"],
            priority: "Mid",
            tags: ["#technical", "#culture"],
            references: [],
            who: [],
        },
        {
            question: "Who on your team has been at the company the longest? How long?",
            potentialAnswers: ["Low turnover in the past hopefully predicts low turnover in the future."],
            priority: "Mid",
            tags: ["#culture", "#issues"],
            followups: [],
            references: [],
            who: [],
        },
        {
            question: "How many people have left in the last year?",
            potentialAnswers: ["Low turnover in the past hopefully predicts low turnover in the future."],
            priority: "Mid",
            tags: ["#culture", "#issues"],
            followups: [],
            references: [],
            who: [],
        },
        {
            question: "How often are you pulled off your primary task?",
            potentialAnswers: [
                "Distractions are costly and multitasking is not efficient. It could also signal overly broad roles, wishy-washy leadership, or understaffing.",
            ],
            priority: "Mid",
            who: ["#engineer"],
            references: ["https://rkoutnik.com/articles/Questions-to-ask-your-interviewer.html"],
            tags: ["#culture", "#issues"],
            followups: [],
        },
        {
            question: "When was your last one-on-one meeting?",
            potentialAnswers: ["Within the last week."],
            references: ["http://randsinrepose.com/archives/the-update-the-vent-and-the-disaster/"],
            priority: "Mid",
            tags: ["#culture", "#management"],
            followups: [],
            who: [],
        },
        {
            question: "What do you not like about your job?",
            followups: ["What stops you from removing it?"],
            potentialAnswers: [],
            priority: "Mid",
            references: [],
            tags: ["#people", "#technical"],
            who: [],
        },
        {
            question: "What are your policies regarding contributing to open source?",
            potentialAnswers: [
                "A demand you not contribute to FOSS projects, especially when on your own time, is a huge red flag for culture. Better would be if contributions are at least not discouraged, best would be officially sanctioned, or even done as part of the job. This will likely be covered in any contract or handbook anyways, but it may be an important signal to find out ahead of time.",
            ],
            followups: [
                "What projects are contributed to officially?",
                'Are there hackathons or a variation of "20% time" where people are encouraged to make these contributions if they want?',
            ],
            priority: "Mid",
            tags: ["#culture", "#issues"],
            references: [],
            who: [],
        },
        {
            question: "What do you use for source control?",
            references: ["http://www.joelonsoftware.com/articles/fog0000000043.html"],
            tags: ["#technical"],
            potentialAnswers: [],
            followups: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "What do you use for a bug / task tracker?",
            potentialAnswers: ["They should have one."],
            followups: ["Is it up to date?"],
            references: ["http://www.joelonsoftware.com/articles/fog0000000043.html"],
            tags: ["#technical", "#process"],
            priority: "unassigned",
            who: [],
        },
        {
            question: "Do you do code reviews? What is the process?",
            potentialAnswers: ["Generally the bigger the company the more process there will be."],
            followups: ["How much time did you spend reviewing code last week?"],
            tags: ["#process"],
            references: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "How do you prioritize features vs. bugs (new development vs. fixing existing code)?",
            potentialAnswers: ["Generally you want to fix bugs before writing new code."],
            references: ["http://www.joelonsoftware.com/articles/fog0000000043.html"],
            tags: ["#process"],
            followups: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "Do you have an up-to-date schedule?",
            potentialAnswers: [
                "Having a schedule forces you to plan and prioritize features and stay on the same page as the rest of the business.",
            ],
            references: ["http://www.joelonsoftware.com/articles/fog0000000043.html"],
            tags: ["#process"],
            followups: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "Do you spec out features before building them? How?",
            potentialAnswers: [
                "Finding and fixing problems is dramatically easier in the design stage. Specs save time and frustration.",
            ],
            references: ["http://www.joelonsoftware.com/articles/fog0000000043.html"],
            tags: ["#process"],
            followups: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "What's the typical noise level where you work?",
            potentialAnswers: ["Quiet space and privacy have well-documented productivity benefits."],
            references: ["http://www.joelonsoftware.com/articles/fog0000000043.html"],
            tags: ["#culture"],
            followups: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "What's the process for ordering new software or hardware?",
            potentialAnswers: [
                "It should be very easy and they should not be stingy about it. The cost of lost productivity is usually greater than the cost of the tools.",
            ],
            references: ["http://www.joelonsoftware.com/articles/fog0000000043.html"],
            tags: ["#culture", "#process"],
            followups: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "Do you have engineers dedicated to building internal tools?",
            potentialAnswers: ["Larger companies should dedicate resources to making their teams more effective."],
            followups: ["Can you describe one of your favorite internal tools?"],
            references: ["http://www.algeri-wong.com/yishan/engineering-management.html"],
            tags: ["#technical"],
            priority: "unassigned",
            who: [],
        },
        {
            question: "What does your QA process look like? Do you have QA engineers?",
            potentialAnswers: [
                "There should be some process; opinions differ on whether engineers should test their own code or have dedicated QA engineers.",
            ],
            references: ["http://www.joelonsoftware.com/articles/fog0000000043.html"],
            tags: ["#process"],
            followups: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "How do you do UX / usability testing?",
            potentialAnswers: [
                "Grabbing five or six people in the hallway is a good start. User studies are even better.",
            ],
            references: ["http://www.joelonsoftware.com/articles/fog0000000043.html"],
            tags: ["#process"],
            followups: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "Are all candidates required to write code during interviews?",
            potentialAnswers: [
                "You should have a good idea from your own experience so far, but you want to make sure there are no exceptions.",
            ],
            references: ["http://www.joelonsoftware.com/articles/fog0000000043.html"],
            tags: ["#hiring"],
            followups: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "Do you do design reviews? Before writing code?",
            potentialAnswers: [
                "In all but the smallest of companies and tasks, getting input from others before starting can save time and effort. Studies show that making changes post-delivery is 5x (for small projects) to >100X (for large projects) more expensive than during requirements definition.",
            ],
            references: ["http://shop.oreilly.com/product/9780596808303.do"],
            tags: ["#process"],
            followups: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "Do you use static analysis?",
            potentialAnswers: [
                "Ideally as part of the build process / CI. Static analysis is shown to catch bugs humans don't.",
            ],
            followups: ["What tool(s)?", "Do static analysis warnings fail the build?"],
            tags: ["#technical", "#process"],
            references: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "What is the makeup of your team? (How many people in what roles?)",
            tags: ["#people", "#culture"],
            potentialAnswers: [],
            followups: [],
            references: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "How many lines of code is your system?",
            potentialAnswers: [
                "This is a basic metric that is surprisingly uncommon to know. Knowing it means it's visible, which means the team values metrics and visibility. Check that it's not wildly outlandish with respect to the system they're building. Beware of positions hiring for one language where the codebase is mostly another, a sign that you may be doing more legacy maintenance than expected.",
            ],
            followups: ["How does that break down by language?"],
            references: [],
            priority: "unassigned",
            tags: [],
            who: [],
        },
        {
            question: "How do you estimate the level of effort (time required) for a task?",
            potentialAnswers: [
                "Have knowledgeable people make independent estimates and take the average (or some reasonable summary).",
            ],
            tags: ["#process"],
            followups: [],
            references: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "How are tech / library / service / vendor choices made?",
            potentialAnswers: ["Ideally via engineering: trying the alternatives and choosing the best."],
            followups: ["Do you feel like you have a significant voice in the process?"],
            tags: ["#process", "#culture"],
            references: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "Do you have regular all-hands meetings?",
            tags: ["#culture"],
            potentialAnswers: [],
            followups: [],
            references: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "Do you have regular team outings / field-trips?",
            tags: ["#culture"],
            potentialAnswers: [],
            followups: [],
            references: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "What is the vacation policy?",
            tags: ["#culture"],
            potentialAnswers: [],
            followups: [],
            references: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "Can you show me some code you're proud of?",
            potentialAnswers: [
                "Craftsmanship and pride in one's work should be part of the company culture. Be wary of teams that aren't proud of anything they've done. Some companies may not allow you to see their code, but they should be able to discuss something they're proud of.",
            ],
            who: ["#engineer"],
            tags: ["#culture"],
            followups: [],
            references: [],
            priority: "unassigned",
        },
        {
            question: "When was the last time you told your boss no?",
            potentialAnswers: [
                "No one is infallible. Look for an environment that welcomes feedback and where people feel comfortable raising concerns up the chain.",
            ],
            followups: ["How did your boss respond?"],
            references: ["http://randsinrepose.com/archives/the-rands-test/"],
            tags: ["#culture", "#management"],
            priority: "unassigned",
            who: [],
        },
        {
            question: "What's your e-mail address?",
            potentialAnswers: [],
            followups: ["May I follow up with you?", "May I ask more questions after the interview?"],
            references: [],
            priority: "unassigned",
            tags: [],
            who: [],
        },
        {
            question: "Given a month of time to work on it, what would you work on in your current product?",
            references: ["https://news.ycombinator.com/item?id=11496962"],
            tags: ["#issues"],
            potentialAnswers: [],
            followups: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "Does your team attend training or conferences more often?",
            potentialAnswers: [
                'Training may indicate a pyramid-shaped team with many junior devs. Conferences indicates somewhere in the middle. "Presents at conferences" can indicate a high percentage of senior staff.',
            ],
            tags: ["#people"],
            who: ["#manager"],
            followups: [],
            references: [],
            priority: "unassigned",
        },
        {
            question: "What's your idea of a good team?",
            tags: ["#culture", "#management"],
            references: ["https://news.ycombinator.com/item?id=11449133"],
            who: ["#manager", "#executive"],
            potentialAnswers: [],
            followups: [],
            priority: "unassigned",
        },
        {
            question: "What surprised you most when you started here?",
            tags: ["#issues"],
            potentialAnswers: [],
            followups: [],
            references: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "What was the last technical disagreement your team had? How was it resolved?",
            tags: ["#culture"],
            potentialAnswers: [],
            followups: [],
            references: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "What are you hoping I'll change?",
            potentialAnswers: [
                "With this question, you're looking for the real job description, as well as signs of wishful thinking. E.g., \"Unit testing is important, and we'd like you to help us get started.\" (If it's important, why aren't they doing it?) Beware expectations of big changes without the authority to make them.",
            ],
            references: ["https://rkoutnik.com/articles/Questions-to-ask-your-interviewer.html"],
            tags: ["#issues"],
            followups: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "How will I get better at my job?",
            potentialAnswers: [
                "Training, conferences, Friday tech talks, mentoring program, etc. Anything beyond platitudes.",
            ],
            references: ["https://rkoutnik.com/articles/Questions-to-ask-your-interviewer.html"],
            tags: ["#culture"],
            followups: [],
            priority: "unassigned",
            who: [],
        },
        {
            question: "Has any of the system been built by contractors or outsourced work?",
            potentialAnswers: ["May be an indicator of personnel issues or low-quality code."],
            followups: ["Any plans for outsourcing or contracting in the future?"],
            tags: ["#culture", "#issues"],
            references: [],
            priority: "unassigned",
            who: [],
        },
        {
            question:
                "Tell me about the last time a deploy broke production. What did you do to prevent it happening again?",
            potentialAnswers: [
                "The details aren't as important as the response: fix the system/process that let the mistake through. Ideally a systematic review of how it happened, addressed as appropriate via more unit testing, code reviews, training, canary testing, monitoring, rollbacks, etc. Preferably not via punishing or firing responsible parties.",
            ],
            tags: ["#process"],
            followups: [],
            references: [],
            priority: "unassigned",
            who: [],
        },
        {
            question:
                "When was the last time you missed or thought you might miss a sprint deadline, and how did you handle it?",
            potentialAnswers: [
                "Cut features, rather than testing or quality. Working longer/harder is not a sustainable solution.",
            ],
            references: ["https://www.salon.com/2012/03/14/bring_back_the_40_hour_work_week/"],
            tags: ["#culture", "#issues"],
            followups: [],
            priority: "unassigned",
            who: [],
        },
        {
            followups: [""],
            potentialAnswers: [],
            priority: "unassigned",
            question: "",
            references: [],
            tags: [],
            who: [],
        },
    ],
    tags: ["#process", "#culture", "#people", "#technical", "#management", "#hiring", "#issues", "#feedback"],
    who: ["#engineer", "#manager", "#executive", "#hr"],
    where: ["#startup", "#big7", "#big100", "#big500"],
};

export type { tPriority, tQuestions, tQuestionsEntity };

export { data };
